[[constraint]]
  name = "github.com/Azure/azure-pipeline-go"
  version = "0.1.8"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.5.0"

[[constraint]]
  name = "github.com/Azure/azure-storage-file-go"
  version = "0.4.1"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "11.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/JeffreyRichter/enum"

[[constraint]]
  name = "github.com/danieljoos/wincred"
  version = "1.0.1"

[[constraint]]
  name = "github.com/jiacfan/keychain"
  version = "0.2.0"

[[constraint]]
  name = "github.com/jiacfan/keyctl"
  version = "0.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[prune]
  go-tests = true
  unused-packages = true
