[[constraint]]
  name = "github.com/Azure/azure-pipeline-go"
  version = "0.1.7"

[[constraint]]
  branch = "master"
  name = "github.com/Azure/azure-storage-blob-go"

[[constraint]]
  name = "github.com/Azure/azure-storage-file-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/JeffreyRichter/enum"

[[constraint]]
  branch = "master"
  name = "github.com/jiacfan/keychain"

[[constraint]]
  branch = "master"
  name = "github.com/jiacfan/keyctl"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[prune]
  go-tests = true
  unused-packages = true
